### ISSUE TITLE
Errors during upgrade/migration from Drupal 7 ("Fatal error: Class 'EntityPlusControllerExportable' not found"...)

### ISSUE THREAD

**Issue by retrodans** [backdrop-contrib/entity_plus#23]
Whilst migrating from Drupal I received the below error:
`Fatal error: Class 'EntityPlusControllerExportable' not found in /app/web/core/modules/entity/entity.module`

As entity_plus was not enabled, I enabled it via the mysql cli (status=1), just to see if that helped.

Sadly though, this then resulted in the below error:
`Call to undefined function entity_metadata_field_text_property_callback()`

I am unsure which issue needs to be resolved sadly, but it feels like a migration bug at this point.

**Comment by laryn** [comment]
Are you able to `grep` your codebase and see where this is coming from? I don't see `EntityPlusControllerExportable` anywhere in the core codebase:
https://github.com/backdrop/backdrop/search?q=EntityPlusControllerExportable&unscoped_q=EntityPlusControllerExportable

Which modules have you got in there? Does the second error mention a filename and line number?

**Comment by laryn** [comment]
FYI I ran into the second error in the Video Embed Field module:
https://github.com/backdrop-contrib/video_embed_field/issues/7

If you can track down where that is from, it should be `entity_plus_metadata_field_text_property_callback` once you've enabled Entity Plus. Filing an issue in whatever module uses that would be good, too.

**Comment by bobchristenson** [comment]
Yup, ran into this with rules just now:
`Fatal error: Class 'EntityPlusControllerExportable' not found in /backdrop/modules/rules/includes/rules.core.inc on line 56`

**Comment by laryn** [comment]
@bobchristenson At this point Entity Plus was not installed, correct? I think this is due to a peculiarity of upgrading modules which include in Backdrop a dependency on Entity Plus (which doesn't formally exist in Drupal 7). Others have proposed simple "stub" modules for Drupal 7 which can be enabled prior to the upgrade to make this end more seamless (so that Entity Plus is pre-enabled), such as this:

 - https://github.com/backdrop-contrib/ubercart/wiki/Upgrading-Ubercart-from-Drupal-7

If you enable Entity Plus at this point, does this error go away?

**Comment by laryn** [comment]
I added further details about upgrading to the Wiki for now.

https://github.com/backdrop-contrib/entity_plus/wiki#migrating-from-drupal-7s-entity-api-module
