### ISSUE TITLE
error when getting date field from wrapper

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/entity_plus#33]
I cannot get a date field from a metada wrapper. I got an error of property missing. I can get any other type of field data, but not a date field type

```
$wrapper = entity_metadata_wrapper('node', $node);
$wrapper->field_description->value() // works fine
$wrapper->field_my_date_field->value() // triggers error field_my_date_field missing
```
Found anyone else in this situation??

**Comment by argiepiano** [comment]
It seems like entity plus does not provide the full metadata property definitions for date field types. And it looks like that is provided in the module Entity Token. If you enable that module, your metadata wrapper should be able to find date fields.

My guess: This integration with Entity Metadata used to exist in the Date contrib module in Drupal. Backdrop integrated Date into core, but did not include the Entity Metadata integration, since Entity Metadata is not core in Backdrop. Someone must have noticed this and added it to Entity Tokens. It would make more sense to have this integration in Entity Plus?

**Comment by laryn** [comment]
@argiepiano Makes sense to me. It looks like Entity Token is seeking maintainers -- by any chance are you interested in picking that up? :innocent:

**Comment by argiepiano** [comment]
@laryn I could give maintaining Entity Tokens a try. What's the process to make that happen? 

Regarding this issue, what would be the best (least harmful) way to move the code needed for date metadata wrappers from Entity Tokens to Entity Plus?  I could do pull requests in both, but we would need to release new versions for the two modules at the same time and hope that people update both together  - otherwise people relying on the Entity Tokens code would lose date metadata functionality, or  may end up with duplicate functionality in both.

**Comment by laryn** [comment]
@argiepiano Regarding the process, see "Adopting Abandoned Projects" here: https://docs.backdropcms.org/documentation/adopt-a-project

In this case it looks like @docwilmot created the project initially so when you create the issue in the queue asking to be added as a maintainer I think you can tag him and ask him to merge the PR that you create over there which adds your name as maintainer.

For the best way to move the code, that's a good question. It looks like Entity Tokens already has a dependency on Entity Plus, so we could make a release of Entity Plus that includes the date wrappers and then make a release of Entity Tokens that does not, which has a dependency on the newest version of Entity Plus. We'd need to test of course...

**Comment by argiepiano** [comment]
@laryn I've created PRs in both modules. HOWEVER I'm noticing that, upon testing, the idea of requiring Entity Token to use a newer version of  Entity Plus by adding the following to `entity_token.info`:

`dependencies[] = entity_plus (>1.x-1.0.13)`

as described [here](https://docs.backdropcms.org/creating-modules) is actually not working. I'm still able to enable the entity_token module despite the fact that I have version 1.0.13 of Entity Plus in my local environment. Has this functionality been implemented in Backdrop core? Am I missing something?

**Comment by laryn** [comment]
@argiepiano I just checked and here's how I've done it elsewhere: `dependencies[] = entity_plus (>=1.0.5)`

**Comment by Wylbur** [comment]
I enabled entity_tokens, and try to set url date tokens, but I am getting this error:
`Error: Call to undefined function entity_metadata_field_verbatim_get() in EntityStructureWrapper->getPropertyValue() (line 440 of /var/www/docroot/modules/entity_plus/includes/entity_plus.wrapper.inc).

Call to undefined function entity_metadata_field_verbatim_get()`

Is this because of the module version mismatch?

**Comment by argiepiano** [comment]
@Wylbur , the current version of Entity Tokens is messy and has many issues, as it was ported a long time and did not get much review or maintenance.  I started maintaining this about a week ago. I'm doing a complete rewrite that includes moving code for date handling to Entity Plus, and avoiding several collisions with core tokens.

I apologize for the  inconvenience. I should be able to release a new version over the weekend.

**Comment by argiepiano** [comment]
@Wylbur , also, can you clarify what you mean by "set url date tokens"?

**Comment by argiepiano** [comment]
@Wylbur BTW if you want a quick fix for that change `entity_metadata_field_verbatim_get()` for `entity_plus_metadata_field_verbatim_get()`

**Comment by argiepiano** [comment]
This issue and also the one mention by @Wylbur above are fixed in the current dev version of Entity Plus.  See #78
