### ISSUE TITLE
Images uploaded into WYSIWYG fields aren't marked permanent

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#35]
Moving https://github.com/backdrop-contrib/paragraphs/issues/65 over here after confirmation that this is an Entity Plus bug.

Images uploaded into WYSIWYG fields are not marked as permanent files and so they disappear when garbage collection runs.

Confirmed in Paragraphs and Registration, which depend on Entity Plus.

@oadaeh:

> I looked at ParagraphsItemController::save() (which was removed in that commit) and compared it with EntityPlusController::save() & EntityStorageControllerInterface::save(). The ParagraphsItemController::save() method is very nearly identical to EntityStorageControllerInterface::save() (there is one addition in ParagraphsItemController::save()) and EntityPlusController::save() has many differences from the other two. Plus, the code in methods that are called from EntityPlusController::save() are also rather different from that which is called from the other to methods.

> So, this is an Entity Plus bug and that code needs to be investigated to locate the change that must be made.

**Comment by laryn** [comment]
Other places this issue has cropped up which may provide insight:

 - https://github.com/backdrop/backdrop-issues/issues/2979#issuecomment-366455143
 - https://github.com/backdrop-contrib/multifield/issues/29

**Comment by laryn** [comment]
Linking some of what @oadaeh was mentioning here for future reference:

 - [ParagraphsItemController::save()](https://github.com/backdrop-contrib/paragraphs/blob/e45d74174c85f1cb63d2bff1e46fcd8f69fc64b2/ParagraphsItemController.inc#L15)
 - [EntityPlusController](https://github.com/backdrop-contrib/entity_plus/blob/1.x/includes/entity_plus.controller.inc#L146)
 - [EntityPlusControllerInterface::save()](https://github.com/backdrop-contrib/entity_plus/blob/1.x/includes/entity_plus.controller.inc#L460)
 - [EntityStorageControllerInterface::save()](https://github.com/backdrop/backdrop/blob/1.x/core/modules/entity/entity.controller.inc#L639)

**Comment by oadaeh** [comment]
I think @hosef found the problem. EntityPlusController::invoke() is called in EntityPlusController::save(). In EntityPlusController::invoke() is this (at line 381 of the 1.0.7 release):
```
        module_invoke_all('entity_plus_' . $hook, $entity, $this->entityType);
```
That means that no entity_$hook functions are being called at that time.

I tried changing that to:
```
        module_invoke_all('entity_' . $hook, $entity, $this->entityType);
```
and it saved the image correctly, marking it permanent.

Since I know that change will not fly, I also tried:
```
        module_invoke_all('entity_' . $hook, $entity, $this->entityType);
        module_invoke_all('entity_plus_' . $hook, $entity, $this->entityType);
```
and:
```
        module_invoke_all('entity_plus_' . $hook, $entity, $this->entityType);
        module_invoke_all('entity_' . $hook, $entity, $this->entityType);
```
and both times it also worked correctly.

I'm sure there might be a downside to one of those last two, like some entity that implements both entity_$hook and entity_plus_$hook and does different things, but I cannot imagine that would be a good idea, so maybe it's not worth considering.

What ever was changed at line 381 would also have to be done at line 961.

Also, as an additional point to mention, none of those changes fixed the problem for the Registration module, so there might be more places where some change like this would need to be made. @hosef would know better about that one, but he's camping until Wednesday.

I also only tested saving new content. I did not test modifying exiting content.

**Comment by laryn** [comment]
I put this into a quick PR. Does this look like what you'd both suggest for a fix to merge?
https://github.com/backdrop-contrib/entity_plus/pull/36

**Comment by oadaeh** [comment]
Yes, that looks good to me.
Joseph's camping and won't be back until late Tuesday, so if you can wait until Wednesday for a response from him, I'll be sure to have him weigh in then.

**Comment by laryn** [comment]
No rush -- I'll patch the site in question and make sure things are working well in the meantime.

**Comment by laryn** [comment]
@hosef Are you comfortable with this as a fix?

**Comment by hosef** [comment]
@laryn Yes, that looks good to me.
