### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#73]
We should set up tests on PRs with GHA and: 

 - make sure that the tests are passing in general
 - Add a date related test (see https://github.com/backdrop-contrib/entity_plus/issues/77)

**Comment by laryn** [comment]
I have basic GHA for tests and coding standards set up (thanks again @indigoxela) and I've started a PR for this particular issue to get tests passing.

**Comment by argiepiano** [comment]
@laryn I have been hard at work these last couple of days fixing several issues that finally allowed the existing tests to pass (NB: I haven't yet tackled the date related test you mentioned above). There are several PRs related to tests.

This is the list of PRs that need to be merged in order to fix the failing tests:

- #74 
- #83 
- #85 
- #89 
- #91
