### ISSUE TITLE
Use langcode instead of language in automated test

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#94]
A small stubborn typo in the test file was preventing the fixed tests to run successfully.  PR coming in a minute.

**Comment by argiepiano** [comment]
PR: #95 

@laryn thank you for merging all the other PRs related to tests. This one should fix the functional tests completely (at least on my local!). 

If you are OK with this I'll go ahead and merge this one, plus two others that add date and link field wrappers. 

It may be time to do a new release? I am almost done rewriting entity_tokens, but it needs to be released at the same time as entity_plus, since I moved code from there to here. I know you have your "fingers in many pies" 😆  so let me know and I'll take care of merging and doing a release.

**Comment by laryn** [comment]
Sounds good! Thanks for all your work here.

 Do you use paragraphs by any chance? There was one other issue I was hoping to solve before a release and I’m stumped. I’m not sure if the problem is entity plus or paragraphs. If you have a chance for a glance it would be amazing — but I understand completely if not!

**Comment by laryn** [comment]
https://github.com/backdrop-contrib/entity_plus/issues/28

**Comment by argiepiano** [comment]
I don't use Paragraphs, but I'll take a look later tonight!
